/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmControl.java
 *
 * Created on 13/10/2009, 08:26:53 AM
 */
package control;

import panimador.PAnimador;

/**
 *
 * @author parmaia
 */
public class frmControl extends javax.swing.JFrame {

  private PAnimador _animador;
  private Juego _juego;

  public frmControl() {
    initComponents();
    _animador = new PAnimador(pnlLienzo);
    _juego = new Juego();
    _animador.agregarAnimable(_juego);
    _animador.agregarAnimable(new Barra());
    _juego.inicializar();
    _animador.iniciar();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlLienzo = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(null);

    pnlLienzo.setBackground(new java.awt.Color(30, 255, 0));
    pnlLienzo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    javax.swing.GroupLayout pnlLienzoLayout = new javax.swing.GroupLayout(pnlLienzo);
    pnlLienzo.setLayout(pnlLienzoLayout);
    pnlLienzoLayout.setHorizontalGroup(
      pnlLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 426, Short.MAX_VALUE)
    );
    pnlLienzoLayout.setVerticalGroup(
      pnlLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 296, Short.MAX_VALUE)
    );

    getContentPane().add(pnlLienzo);
    pnlLienzo.setBounds(10, 10, 430, 300);

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-453)/2, (screenSize.height-350)/2, 453, 350);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new frmControl().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel pnlLienzo;
  // End of variables declaration//GEN-END:variables
}
