
package animacion;

import panimador.PAnimador;

/**
 *
 * @author parmaia
 */
public class frmAnimacion extends javax.swing.JFrame {
    private PAnimador _animador;

    /** Creates new form frmAnimacion */
    public frmAnimacion() {
      initComponents();
      _animador = new PAnimador(lienzo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lienzo = new javax.swing.JPanel();
    btnIniciar = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(null);

    javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
    lienzo.setLayout(lienzoLayout);
    lienzoLayout.setHorizontalGroup(
      lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 330, Short.MAX_VALUE)
    );
    lienzoLayout.setVerticalGroup(
      lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );

    getContentPane().add(lienzo);
    lienzo.setBounds(10, 20, 330, 400);

    btnIniciar.setText("Iniciar");
    btnIniciar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnIniciarActionPerformed(evt);
      }
    });
    getContentPane().add(btnIniciar);
    btnIniciar.setBounds(350, 20, 90, 29);

    jButton1.setText("Agregar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1);
    jButton1.setBounds(350, 50, 90, 29);

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-458)/2, (screenSize.height-459)/2, 458, 459);
  }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
      // TODO add your handling code here:
      //_animador.detener();
      _animador.clear();
      _animador.antialiasing(true);
      for(int i=0;i<20;i++)
        _animador.agregarAnimable(new Pelota(lienzo.getWidth(),lienzo.getHeight()));
      _animador.iniciar();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
      _animador.agregarAnimable(new Pelota(lienzo.getWidth(),lienzo.getHeight()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnimacion().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnIniciar;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel lienzo;
  // End of variables declaration//GEN-END:variables

}
